/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.cronops;import cn.zhuatech.cronops.service.CronAnalysisService;import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;/**
                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                       */
class CronAnalysisServiceTests{private final CronAnalysisService s=new CronAnalysisService();/**
                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                    */
@Test void estimatesFifteenMinuteSchedule(){var r=s.analyze(new CronAnalysisService.Request("*/15 * * * *",1,2,true,true));assertTrue(r.valid());assertEquals(96,r.estimatedRunsPerDay());assertEquals("SAFE",r.status());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
@Test void rejectsSixFields(){assertFalse(s.analyze(new CronAnalysisService.Request("0 0 * * * *",1,1,true,true)).valid());}}
