/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.cronops.controller;import cn.zhuatech.cronops.service.CronAnalysisService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                */
@RestController @RequestMapping("/api/cronops") @CrossOrigin public class CronAnalysisController{private final CronAnalysisService s;/**
                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                     */
public CronAnalysisController(CronAnalysisService s){this.s=s;}/**
                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                    */
@PostMapping("/analyze") CronAnalysisService.Result analyze(@Valid @RequestBody CronAnalysisService.Request r){return s.analyze(r);}}
